server:
  port: 8081

spring:
  application:
    name: collector-binance
  kafka:
    bootstrap-servers: localhost:9092

binance:
  websocket:
    base-url: wss://fstream.binance.com/public/stream
    symbols: BTCUSDT
    kline-interval: 15m
