server:
  port: 8082

spring:
  application:
    name: alpaca-collector-service
  kafka:
    bootstrap-servers: localhost:9092

alpaca:
  websocket:
    url: wss://stream.data.alpaca.markets/v2/iex
    key: ${ALPACA_API_KEY}
    secret: ${ALPACA_SECRET_KEY}
    symbols: AAPL,MSFT,NVDA,TSLA,AMZN