server:
  port: 8081

spring:
  application:
    name: binance-collector-service
  kafka:
    bootstrap-servers: localhost:9092

binance:
  websocket:
    base-url: wss://stream.binance.com:9443/stream
    symbols: BTCUSDT
    kline-interval: 1m
    depth-levels: 20
    depth-update-interval: 100ms
